import {
    AlertTriangle,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    Bell,
    Bookmark,
    Briefcase,
    Brush,
    Calendar,
    Camera,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    Clock,
    CreditCard,
    Crown,
    Download,
    Droplets,
    ExternalLink,
    Eye,
    Filter,
    Globe,
    Hammer,
    Heart,
    Inbox,
    Info,
    Key,
    LayoutDashboard,
    Link as LinkIcon,
    LogOut,
    Mail,
    MapPin,
    MessageSquare,
    Minus,
    MoreHorizontal,
    Package,
    Paperclip,
    Pause,
    Pencil,
    Phone,
    Plus,
    RefreshCw,
    Search,
    Send,
    Settings,
    Shield,
    ShieldCheck,
    Sparkles,
    Star,
    StarHalf,
    Trash2,
    TrendingDown,
    TrendingUp,
    Truck,
    Upload,
    User,
    Users,
    Wind,
    X,
    Zap,
    Leaf,
    Bug,
    Baby,
    Dog,
    Home,
    type LucideIcon,
} from 'lucide-react';

/**
 * Mapeo del icon-set del prototipo Hireeo (HIcon) a componentes de lucide-react.
 * Los nombres a la izquierda son los del DS original; los componentes a la derecha
 * son los más cercanos visualmente disponibles en Lucide.
 */
export const HIRE_ICONS = {
    arrow: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUR: ArrowUpRight,
    arrowDR: ArrowDownRight,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    check: Check,
    x: X,
    plus: Plus,
    minus: Minus,
    search: Search,
    filter: Filter,
    pin: MapPin,
    star: Star,
    starHalf: StarHalf,
    zap: Zap,
    shield: Shield,
    shieldCheck: ShieldCheck,
    clock: Clock,
    calendar: Calendar,
    user: User,
    users: Users,
    bell: Bell,
    settings: Settings,
    logout: LogOut,
    heart: Heart,
    chat: MessageSquare,
    send: Send,
    more: MoreHorizontal,
    edit: Pencil,
    trash: Trash2,
    eye: Eye,
    download: Download,
    upload: Upload,
    globe: Globe,
    layoutDash: LayoutDashboard,
    briefcase: Briefcase,
    card: CreditCard,
    trend: TrendingUp,
    trendDown: TrendingDown,
    sparkle: Sparkles,
    crown: Crown,
    bolt: Zap,
    inbox: Inbox,
    pkg: Package,
    hammer: Hammer,
    brush: Brush,
    truck: Truck,
    droplet: Droplets,
    wind: Wind,
    key: Key,
    external: ExternalLink,
    info: Info,
    alert: AlertTriangle,
    bookmark: Bookmark,
    cam: Camera,
    paperclip: Paperclip,
    phone: Phone,
    mail: Mail,
    link: LinkIcon,
    refresh: RefreshCw,
    pause: Pause,
    leaf: Leaf,
    bug: Bug,
    baby: Baby,
    dog: Dog,
    home: Home,
} as const satisfies Record<string, LucideIcon>;

export type HireIconName = keyof typeof HIRE_ICONS;

export const HIRE_ICON_NAMES = Object.keys(HIRE_ICONS) as readonly HireIconName[];
