import {
    AlertTriangle,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    Baby,
    Bell,
    Bookmark,
    Briefcase,
    Brush,
    Bug,
    Calendar,
    Camera,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    Clock,
    CreditCard,
    Crown,
    Dog,
    Download,
    Droplets,
    Edit2,
    ExternalLink,
    Eye,
    FileText,
    Filter,
    Globe,
    Hammer,
    Heart,
    Home,
    Inbox,
    Info,
    Key,
    Languages,
    LayoutDashboard,
    Leaf,
    Link,
    LogOut,
    Mail,
    MapPin,
    MessageSquare,
    Minus,
    MoreHorizontal,
    Package,
    Paperclip,
    Pause,
    Pencil,
    Phone,
    Plus,
    RefreshCw,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    ShieldCheck,
    Sparkles,
    Star,
    StarHalf,
    Trash2,
    TrendingDown,
    TrendingUp,
    Truck,
    Upload,
    User,
    Users,
    Wind,
    X,
    Zap,
} from '@/shared/components/icons';
import type { SvgIconComponent } from '@/shared/components/icons';

/**
 * Mapeo del icon-set del prototipo Hireeo (HIcon) a componentes SVG inline.
 * Los nombres a la izquierda son los del DS original.
 */
export const HIRE_ICONS = {
    arrow: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUR: ArrowUpRight,
    arrowDR: ArrowDownRight,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    check: Check,
    x: X,
    plus: Plus,
    minus: Minus,
    search: Search,
    filter: Filter,
    pin: MapPin,
    star: Star,
    starHalf: StarHalf,
    zap: Zap,
    shield: Shield,
    shieldCheck: ShieldCheck,
    clock: Clock,
    calendar: Calendar,
    user: User,
    users: Users,
    bell: Bell,
    settings: Settings,
    logout: LogOut,
    heart: Heart,
    chat: MessageSquare,
    send: Send,
    more: MoreHorizontal,
    edit: Pencil,
    trash: Trash2,
    eye: Eye,
    download: Download,
    upload: Upload,
    globe: Globe,
    layoutDash: LayoutDashboard,
    briefcase: Briefcase,
    card: CreditCard,
    trend: TrendingUp,
    trendDown: TrendingDown,
    sparkle: Sparkles,
    crown: Crown,
    bolt: Zap,
    inbox: Inbox,
    pkg: Package,
    hammer: Hammer,
    brush: Brush,
    truck: Truck,
    droplet: Droplets,
    wind: Wind,
    key: Key,
    external: ExternalLink,
    info: Info,
    alert: AlertTriangle,
    bookmark: Bookmark,
    cam: Camera,
    paperclip: Paperclip,
    phone: Phone,
    mail: Mail,
    link: Link,
    refresh: RefreshCw,
    pause: Pause,
    leaf: Leaf,
    bug: Bug,
    baby: Baby,
    dog: Dog,
    home: Home,
    fileText: FileText,
    languages: Languages,
} as const satisfies Record<string, SvgIconComponent>;

export type HireIconName = keyof typeof HIRE_ICONS;

export const HIRE_ICON_NAMES = Object.keys(HIRE_ICONS) as readonly HireIconName[];
