import type { Connection } from './types';

export const CONNECTIONS: Connection[] = [
    {
        id: 'e-proxy-pages',
        from: 'infra.proxy',
        to: 'infra.countryProvider',
        protocol: 'https',
        label: 'país en URL',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'e-authjs-auth',
        from: 'infra.authjs',
        to: 'module.auth',
        protocol: 'jwt',
        label: 'login / oauth / refresh',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'e-client-api',
        from: 'infra.apiClient',
        to: 'infra.guards',
        protocol: 'api-key',
        label: 'x-api-key + Bearer',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'e-guards-modules',
        from: 'infra.guards',
        to: 'module.services',
        protocol: 'https',
        label: '/api/v1',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'e-modules-prisma',
        from: 'module.services',
        to: 'infra.prisma',
        protocol: 'prisma',
        label: 'ORM',
        perspectives: ['tecnica'],
    },
    {
        id: 'e-prisma-pg',
        from: 'infra.prisma',
        to: 'infra.postgres',
        protocol: 'prisma',
        label: 'SQL',
        perspectives: ['tecnica'],
    },
    {
        id: 'e-chat-ws',
        from: 'feature.chat',
        to: 'infra.websocket',
        protocol: 'websocket',
        label: 'namespace /chat',
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'e-ws-gateway',
        from: 'infra.websocket',
        to: 'module.chat',
        protocol: 'websocket',
        label: 'JWT handshake',
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'e-wh-sub',
        from: 'infra.webhooks',
        to: 'module.subscriptions',
        protocol: 'webhook',
        label: 'raw body + firma',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'e-sub-mp',
        from: 'module.payments',
        to: 'ext.mercadopago',
        protocol: 'sdk',
        label: 'cl ar uy',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'e-sub-st',
        from: 'module.payments',
        to: 'ext.stripe',
        protocol: 'sdk',
        label: 'es us',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'e-kyc-st',
        from: 'module.kyc',
        to: 'ext.stripeKyc',
        protocol: 'sdk',
        label: 'Identity',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'e-up-cloud',
        from: 'module.upload',
        to: 'ext.cloudinary',
        protocol: 'sdk',
        label: 'imagenes',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'e-bot-gem',
        from: 'module.chatbot',
        to: 'ext.gemini',
        protocol: 'sdk',
        label: 'detect-category',
        perspectives: ['cliente', 'tecnica'],
    },
    {
        id: 'e-mobile-sr',
        from: 'actor.mobile',
        to: 'module.serviceRequests',
        protocol: 'https',
        label: 'alta de pedido',
        perspectives: ['profesional', 'tecnica'],
    },
];
