import type { Entity } from './types';

export const ENTITIES: Entity[] = [
    {
        id: 'entity.Country',
        title: 'Country',
        subtitle: 'active · paymentsEnabled · moneda',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'entity.GeoRegion',
        title: 'GeoRegion',
        subtitle: 'región del país',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'tecnica'],
    },
    {
        id: 'entity.GeoLocality',
        title: 'GeoLocality',
        subtitle: 'comuna / ciudad + lat/lng',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'tecnica'],
    },
    {
        id: 'entity.User',
        title: 'User',
        subtitle: 'incluye kycStatus · sin tabla KYC',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
        note: 'KYC no tiene model propio.',
    },
    {
        id: 'entity.UserRole',
        title: 'UserRole',
        subtitle: 'rol por país',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'entity.Service',
        title: 'Service',
        subtitle: 'BASIC/PREMIUM · endDate 12 meses',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'entity.Subscription',
        title: 'Subscription',
        subtitle: 'Pro por servicio, no por user',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'entity.Rating',
        title: 'Rating',
        subtitle: 'PENDING hasta el admin',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'entity.Favorite',
        title: 'Favorite',
        subtitle: 'user ↔ service',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'tecnica'],
    },
    {
        id: 'entity.Conversation',
        title: 'Conversation',
        subtitle: 'chat de un servicio',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'entity.Message',
        title: 'Message',
        subtitle: 'mensajes Socket.IO',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'entity.ServiceRequest',
        title: 'ServiceRequest',
        subtitle: 'alta desde mobile/API',
        path: 'backend/prisma/schema.prisma',
        status: 'mobile-only',
        perspectives: ['profesional', 'cliente', 'tecnica'],
        note: 'La web lista y cotiza; no crea el pedido.',
    },
    {
        id: 'entity.Quote',
        title: 'Quote',
        subtitle: 'PENDING → ACCEPTED',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'entity.PremiumPrice',
        title: 'PremiumPrice',
        subtitle: 'país + duración 1|3|6|9|12',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'entity.Integration',
        title: 'Integration',
        subtitle: 'keys cifradas por provider',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['superadmin', 'tecnica'],
    },
    {
        id: 'entity.Interaction',
        title: 'Interaction',
        subtitle: 'VIEW_PHONE CALL WHATSAPP',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        perspectives: ['cliente', 'admin', 'superadmin', 'tecnica'],
    },
];
