import type { Process } from './types';

export const PROCESSES: Process[] = [
    {
        id: 'cliente.pais',
        title: 'Entrada y país',
        summary: 'El proxy decide /cl /ar /uy /es /us y el layout carga CountryProvider.',
        perspective: 'cliente',
        steps: [
            {
                id: 'c-pais-1',
                label: 'Request a hireeo.app',
                detail: 'Si el path es /, detectCountry redirige al país.',
                nodeIds: ['actor.client', 'infra.proxy'],
                status: 'live',
            },
            {
                id: 'c-pais-2',
                label: 'Layout del país',
                detail: 'GET /geo/countries/:code. Si active=false → Coming soon.',
                nodeIds: ['infra.countryProvider', 'feature.geo', 'module.geo', 'entity.Country'],
                status: 'live',
            },
            {
                id: 'c-pais-3',
                label: 'Home',
                detail: 'HeroSearchBar, categorías y ChatIA.',
                nodeIds: ['route.home', 'feature.home'],
                status: 'live',
            },
        ],
    },
    {
        id: 'cliente.auth',
        title: 'Autenticación',
        summary: 'Auth.js no es la fuente de verdad. Nest emite JWT; Next guarda la sesión.',
        perspective: 'cliente',
        steps: [
            {
                id: 'c-auth-1',
                label: 'Login / register',
                detail: 'Email+password o Google / Apple / Microsoft.',
                nodeIds: ['route.login', 'feature.auth', 'infra.authjs', 'ext.google'],
                status: 'live',
            },
            {
                id: 'c-auth-2',
                label: 'Nest /auth',
                detail: 'access ~15 min + refresh ~30 d + roles por país.',
                nodeIds: ['module.auth', 'infra.guards', 'entity.User', 'entity.UserRole'],
                status: 'live',
            },
            {
                id: 'c-auth-3',
                label: 'redirectByRole',
                detail: 'Client/Pro → /profile · Admin → /admin · SuperAdmin → /config.',
                nodeIds: ['feature.auth', 'route.profile'],
                status: 'live',
            },
        ],
    },
    {
        id: 'cliente.busqueda',
        title: 'Buscar un profesional',
        summary: 'Texto + geo → listado ordenado por featured y rating.',
        perspective: 'cliente',
        steps: [
            {
                id: 'c-search-1',
                label: 'Oficio y lugar',
                detail: 'Gemini detect-category o keywords; GPS/CP → GET /geo/resolve.',
                nodeIds: ['route.home', 'feature.home', 'module.chatbot', 'ext.gemini', 'module.geo'],
                status: 'live',
            },
            {
                id: 'c-search-2',
                label: 'GET /services',
                detail: 'active + endDate vigente. Filtros de región, localidad, radio.',
                nodeIds: ['route.search', 'feature.services', 'module.services', 'entity.Service'],
                status: 'live',
            },
            {
                id: 'c-search-3',
                label: 'Ficha',
                detail: 'Si el país del servicio ≠ URL, redirect canónico.',
                nodeIds: ['route.service', 'entity.GeoLocality'],
                status: 'live',
            },
        ],
    },
    {
        id: 'cliente.ficha',
        title: 'Ficha, chat, reseña, favorito',
        summary: 'Desde la ficha el cliente conversa, califica y guarda.',
        perspective: 'cliente',
        steps: [
            {
                id: 'c-ficha-1',
                label: 'Abrir ficha',
                detail: 'GET /services/:slug. Galería, about, precio, related.',
                nodeIds: ['route.service', 'feature.services', 'module.services', 'entity.Service'],
                status: 'live',
            },
            {
                id: 'c-ficha-2',
                label: 'Chat',
                detail: 'POST /chat/conversations + Socket.IO /chat. Sin sesión → /login.',
                nodeIds: [
                    'feature.chat',
                    'module.chat',
                    'infra.websocket',
                    'entity.Conversation',
                    'entity.Message',
                ],
                status: 'live',
            },
            {
                id: 'c-ficha-3',
                label: 'Teléfono / WhatsApp',
                detail: 'POST /interactions VIEW_PHONE CALL WHATSAPP.',
                nodeIds: ['module.interactions', 'entity.Interaction'],
                status: 'live',
            },
            {
                id: 'c-ficha-4',
                label: 'Favorito y reseña',
                detail: 'Reseña nace PENDING. El admin la pasa a ACTIVE y recalcula promedio.',
                nodeIds: [
                    'feature.favorites',
                    'module.favorites',
                    'entity.Favorite',
                    'feature.reviews',
                    'module.ratings',
                    'entity.Rating',
                ],
                status: 'live',
            },
        ],
    },
    {
        id: 'cliente.quotes',
        title: 'Cotizaciones y escrow',
        summary: 'El cliente no crea el pedido. Lista, acepta y paga.',
        perspective: 'cliente',
        steps: [
            {
                id: 'c-q-1',
                label: 'Ver quotes',
                detail: 'GET /quotes/request/:id en /profile/quotes.',
                nodeIds: ['route.quotes', 'feature.services', 'module.quotes', 'entity.Quote'],
                status: 'live',
            },
            {
                id: 'c-q-2',
                label: 'Aceptar',
                detail: 'PATCH /quotes/:id/accept → ACCEPTED.',
                nodeIds: ['module.quotes', 'entity.ServiceRequest'],
                status: 'live',
            },
            {
                id: 'c-q-3',
                label: 'Escrow',
                detail: 'POST /escrow/checkout. Split 15/85. Connect no implementado.',
                nodeIds: ['module.escrow', 'ext.mercadopago', 'ext.stripe'],
                status: 'mock',
            },
        ],
    },
    {
        id: 'pro.publish',
        title: 'Publicar un servicio',
        summary: 'El anuncio queda BASIC activo 12 meses al crear. No hay cola de aprobación.',
        perspective: 'profesional',
        steps: [
            {
                id: 'p-pub-1',
                label: 'Wizard /publish',
                detail: 'Sin sesión: registra usuario temporal. Con sesión: arranca en oficio.',
                nodeIds: ['actor.professional', 'route.publish', 'feature.services', 'feature.auth'],
                status: 'live',
            },
            {
                id: 'p-pub-2',
                label: 'Fotos e IA',
                detail: '/api/upload → Cloudinary. Descripción opcional con Gemini.',
                nodeIds: ['module.upload', 'ext.cloudinary', 'ext.gemini'],
                status: 'live',
            },
            {
                id: 'p-pub-3',
                label: 'POST /services',
                detail: 'active=true, level=BASIC, endDate +12 meses. Visible al toque.',
                nodeIds: ['module.services', 'entity.Service', 'infra.apiClient'],
                status: 'live',
            },
        ],
    },
    {
        id: 'pro.pago',
        title: 'Pago Hireeo Pro',
        summary: 'Importe lo resuelve el backend con PremiumPrice. Gateway según país.',
        perspective: 'profesional',
        steps: [
            {
                id: 'p-pay-1',
                label: 'Elegir duración',
                detail: 'GET /prices. Si paymentsEnabled=false el wizard no ofrece Pro.',
                nodeIds: ['feature.payments', 'module.prices', 'entity.PremiumPrice'],
                status: 'live',
            },
            {
                id: 'p-pay-2',
                label: 'Checkout',
                detail: 'cl/ar/uy MercadoPago Brick. es/us Stripe Elements.',
                nodeIds: [
                    'module.subscriptions',
                    'module.payments',
                    'ext.mercadopago',
                    'ext.stripe',
                    'entity.Subscription',
                ],
                status: 'live',
            },
            {
                id: 'p-pay-3',
                label: 'Webhook',
                detail: 'Next reenvía raw body. Nest verifica firma → PREMIUM + featured.',
                nodeIds: ['infra.webhooks', 'module.subscriptions', 'entity.Service'],
                status: 'live',
            },
        ],
    },
    {
        id: 'pro.leads',
        title: 'Leads y cotizaciones',
        summary: 'El pedido nace en mobile/API. El pro lo ve y cotiza.',
        perspective: 'profesional',
        steps: [
            {
                id: 'p-lead-1',
                label: 'Alta del pedido',
                detail: 'POST /service-requests no existe en la web Next.',
                nodeIds: ['actor.mobile', 'module.serviceRequests', 'entity.ServiceRequest'],
                status: 'mobile-only',
            },
            {
                id: 'p-lead-2',
                label: 'Feed del pro',
                detail: 'GET /service-requests/available mismas categorías.',
                nodeIds: ['route.leads', 'feature.services', 'module.serviceRequests'],
                status: 'live',
            },
            {
                id: 'p-lead-3',
                label: 'Cotizar',
                detail: 'POST /quotes · request pasa a QUOTED.',
                nodeIds: ['module.quotes', 'entity.Quote'],
                status: 'live',
            },
        ],
    },
    {
        id: 'pro.kyc',
        title: 'Verificación KYC',
        summary: 'Stripe Identity hosted. Estado en User, no hay tabla Kyc.',
        perspective: 'profesional',
        steps: [
            {
                id: 'p-kyc-1',
                label: 'Pedir sesión',
                detail: 'GET /kyc/status · POST /kyc/session.',
                nodeIds: ['route.verification', 'feature.users', 'module.kyc', 'entity.User'],
                status: 'live',
            },
            {
                id: 'p-kyc-2',
                label: 'Stripe Identity',
                detail: 'Hosted flow. Webhook firma raw body. VERIFIED es terminal.',
                nodeIds: ['ext.stripeKyc', 'module.kyc'],
                status: 'live',
            },
        ],
    },
    {
        id: 'pro.become',
        title: 'Client → Professional',
        summary: 'No ocurre al publicar. Modal de perfil: borra Client, crea Professional.',
        perspective: 'profesional',
        steps: [
            {
                id: 'p-bec-1',
                label: 'Modal de perfil',
                detail: 'POST /users/me/become-provider en el mismo país.',
                nodeIds: ['route.profile', 'feature.users', 'module.users', 'entity.UserRole'],
                status: 'live',
            },
        ],
    },
    {
        id: 'admin.moderar',
        title: 'Moderar el país',
        summary: 'Admin del país entra a /{país}/admin. SuperAdmin también puede.',
        perspective: 'admin',
        steps: [
            {
                id: 'a-1',
                label: 'Guard de layout',
                detail: 'Sin token → /login. País distinto → /unauthorized.',
                nodeIds: ['actor.admin', 'route.login', 'infra.proxy', 'route.admin'],
                status: 'live',
            },
            {
                id: 'a-2',
                label: 'Catálogo scoped',
                detail: 'users, services active/featured, ratings, categories, sponsors.',
                nodeIds: [
                    'feature.admin',
                    'module.services',
                    'module.ratings',
                    'module.categories',
                    'entity.Service',
                    'entity.Rating',
                ],
                status: 'live',
            },
            {
                id: 'a-3',
                label: 'Aprobar reseña',
                detail: 'PATCH /ratings/:id PENDING → ACTIVE. Recalcula averageRating.',
                nodeIds: ['feature.reviews', 'module.ratings', 'entity.Rating'],
                status: 'live',
            },
            {
                id: 'a-4',
                label: 'Toggle de pagos',
                detail: 'PATCH /geo/countries/:code/payments.',
                nodeIds: ['module.geo', 'entity.Country'],
                status: 'live',
            },
        ],
    },
    {
        id: 'sa.config',
        title: 'Configuración global',
        summary: '/config es el admin mundial: países, keys y el catálogo cruzado.',
        perspective: 'superadmin',
        steps: [
            {
                id: 'sa-1',
                label: 'Login SuperAdmin',
                detail: 'redirectByRole → /config. Layout solo SuperAdmin.',
                nodeIds: ['actor.superadmin', 'route.login', 'feature.auth', 'route.config'],
                status: 'live',
            },
            {
                id: 'sa-2',
                label: 'Países',
                detail: 'active, paymentsEnabled, labels.',
                nodeIds: ['feature.configuration', 'module.geo', 'entity.Country'],
                status: 'live',
            },
            {
                id: 'sa-3',
                label: 'Integraciones',
                detail: '11 providers: pagos, KYC, OAuth, Gemini, Cloudinary, Firebase, Brevo.',
                nodeIds: ['feature.integrations', 'module.integrations', 'entity.Integration'],
                status: 'live',
            },
            {
                id: 'sa-4',
                label: 'Catálogo global',
                detail: 'users, services, ratings, payments, premium-prices, app-users.',
                nodeIds: ['feature.admin', 'module.users', 'module.services', 'module.prices'],
                status: 'live',
            },
        ],
    },
    {
        id: 'tec.pipeline',
        title: 'Pipeline de un request',
        summary: 'Browser → proxy → Server Actions → apiClient → guards → Prisma.',
        perspective: 'tecnica',
        steps: [
            {
                id: 't-1',
                label: 'proxy.ts',
                detail: 'País, legacy redirects, guards de /admin y /profile.',
                nodeIds: ['infra.proxy', 'infra.countryProvider'],
                status: 'live',
            },
            {
                id: 't-2',
                label: 'Auth.js + apiClient',
                detail: 'JWT en sesión. x-api-key solo SSR.',
                nodeIds: ['infra.authjs', 'infra.apiClient', 'module.auth'],
                status: 'live',
            },
            {
                id: 't-3',
                label: 'Guards Nest',
                detail: 'Throttler 10/s · ApiKey · JWT · Roles. Webhooks son @Public + firma.',
                nodeIds: ['infra.guards', 'infra.webhooks'],
                status: 'live',
            },
            {
                id: 't-4',
                label: 'Prisma → Postgres',
                detail: '24 models. KYC y escrow no tienen tabla propia.',
                nodeIds: ['infra.prisma', 'infra.postgres', 'entity.Service', 'entity.User'],
                status: 'live',
            },
        ],
    },
    {
        id: 'tec.pagos',
        title: 'Pasarelas y webhooks',
        summary: 'Gateway por país. Next no verifica firma.',
        perspective: 'tecnica',
        steps: [
            {
                id: 'tp-1',
                label: 'Elegir gateway',
                detail: 'Country.gateway: MP en LATAM, Stripe en ES/US.',
                nodeIds: ['entity.Country', 'module.payments', 'ext.mercadopago', 'ext.stripe'],
                status: 'live',
            },
            {
                id: 'tp-2',
                label: 'Checkout',
                detail: 'POST /subscriptions. Importe desde PremiumPrice, no del browser.',
                nodeIds: ['module.subscriptions', 'module.prices', 'entity.Subscription'],
                status: 'live',
            },
            {
                id: 'tp-3',
                label: 'Webhook',
                detail: 'frontend/api/webhooks/* reenvía. Nest verifica y marca PREMIUM.',
                nodeIds: ['infra.webhooks', 'module.subscriptions', 'entity.Service'],
                status: 'live',
            },
        ],
    },
    {
        id: 'tec.chat',
        title: 'Realtime chat',
        summary: 'REST crea la conversación. Socket.IO mueve los mensajes.',
        perspective: 'tecnica',
        steps: [
            {
                id: 'tc-1',
                label: 'POST /chat/conversations',
                detail: 'JWT + serviceId → conversationId.',
                nodeIds: ['feature.chat', 'module.chat', 'entity.Conversation'],
                status: 'live',
            },
            {
                id: 'tc-2',
                label: 'Handshake /chat',
                detail: 'JWT · join user:id · send_message / mark_read.',
                nodeIds: ['infra.websocket', 'entity.Message'],
                status: 'live',
            },
        ],
    },
];
