import type { CatalogItem } from './types';

const P_CLIENT: CatalogItem['perspectives'] = ['cliente', 'tecnica'];
const P_PRO: CatalogItem['perspectives'] = ['profesional', 'tecnica'];
const P_ADMIN: CatalogItem['perspectives'] = ['admin', 'tecnica'];
const P_SA: CatalogItem['perspectives'] = ['superadmin', 'tecnica'];
const P_ALL: CatalogItem['perspectives'] = [
    'cliente',
    'profesional',
    'admin',
    'superadmin',
    'tecnica',
];

export const SURFACES: CatalogItem[] = [
    {
        id: 'infra.proxy',
        kind: 'infra',
        title: 'proxy.ts',
        subtitle: 'cookie → CF → Vercel → idioma → cl',
        path: 'frontend/src/proxy.ts',
        status: 'live',
        layers: ['surfaces', 'connections'],
        perspectives: P_ALL,
    },
    {
        id: 'infra.countryProvider',
        kind: 'infra',
        title: 'CountryProvider',
        subtitle: 'moneda, gateway, labels, active',
        path: 'frontend/src/lib/providers/CountryProvider.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_ALL,
    },
    {
        id: 'infra.authjs',
        kind: 'infra',
        title: 'Auth.js',
        subtitle: 'sesión; JWT Nest en cookie',
        path: 'frontend/src/app/api/auth/[...nextauth]/route.ts',
        status: 'live',
        layers: ['surfaces', 'connections'],
        perspectives: P_ALL,
    },
    {
        id: 'infra.apiClient',
        kind: 'infra',
        title: 'apiClient',
        subtitle: 'x-api-key SSR · Bearer JWT',
        path: 'frontend/src/lib/api/apiClient.ts',
        status: 'live',
        layers: ['domain', 'connections'],
        perspectives: P_ALL,
        note: 'Nunca manda API_KEY al browser.',
    },
    {
        id: 'infra.guards',
        kind: 'infra',
        title: 'Guards Nest',
        subtitle: 'Throttler → ApiKey → JWT → Roles',
        path: 'backend/src/common/guards/',
        status: 'live',
        layers: ['domain', 'connections'],
        perspectives: P_ALL,
    },
    {
        id: 'infra.websocket',
        kind: 'infra',
        title: 'Socket.IO /chat',
        subtitle: 'handshake JWT · rooms user:id',
        path: 'backend/src/modules/chat/chat.gateway.ts',
        status: 'live',
        layers: ['connections'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'infra.webhooks',
        kind: 'infra',
        title: 'Webhooks Next',
        subtitle: 'reenvían raw body, no verifican',
        path: 'frontend/src/app/api/webhooks/',
        status: 'live',
        layers: ['connections'],
        perspectives: ['profesional', 'tecnica'],
        note: 'La firma se verifica en Nest.',
    },
    {
        id: 'infra.prisma',
        kind: 'infra',
        title: 'Prisma 7',
        subtitle: 'ORM · fuente de verdad',
        path: 'backend/prisma/schema.prisma',
        status: 'live',
        layers: ['data', 'connections'],
        perspectives: P_ALL,
    },
    {
        id: 'infra.postgres',
        kind: 'infra',
        title: 'PostgreSQL 16',
        subtitle: 'puerto 5435 local',
        path: 'docker-database/',
        status: 'live',
        layers: ['data'],
        perspectives: P_ALL,
    },

    {
        id: 'route.home',
        kind: 'route',
        title: '/{país}',
        subtitle: 'Home + ChatIA',
        path: 'frontend/src/app/(country)/[country]/(public)/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_CLIENT,
    },
    {
        id: 'route.search',
        kind: 'route',
        title: '/{país}/search',
        subtitle: 'Listado filtrado',
        path: 'frontend/src/app/(country)/[country]/(public)/search/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_CLIENT,
    },
    {
        id: 'route.service',
        kind: 'route',
        title: '/{país}/service/[slug]',
        subtitle: 'Ficha del anuncio',
        path: 'frontend/src/app/(country)/[country]/(public)/service/[slug]/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'route.publish',
        kind: 'route',
        title: '/{país}/publish',
        subtitle: 'Wizard Publicar',
        path: 'frontend/src/app/(country)/[country]/(public)/publish/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_PRO,
    },
    {
        id: 'route.login',
        kind: 'route',
        title: '/login /register',
        subtitle: 'Auth global',
        path: 'frontend/src/app/(auth)/',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_ALL,
    },
    {
        id: 'route.profile',
        kind: 'route',
        title: '/{país}/profile',
        subtitle: 'Cuenta',
        path: 'frontend/src/app/(country)/[country]/(account)/profile/',
        status: 'live',
        layers: ['surfaces'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'route.quotes',
        kind: 'route',
        title: '/profile/quotes',
        subtitle: 'Cotizaciones del cliente',
        path: 'frontend/src/app/(country)/[country]/(account)/profile/quotes/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_CLIENT,
    },
    {
        id: 'route.leads',
        kind: 'route',
        title: '/profile/leads',
        subtitle: 'Pedidos para el pro',
        path: 'frontend/src/app/(country)/[country]/(account)/profile/leads/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_PRO,
    },
    {
        id: 'route.messages',
        kind: 'route',
        title: '/profile/messages',
        subtitle: 'Bandeja chat',
        path: 'frontend/src/app/(country)/[country]/(account)/profile/messages/',
        status: 'live',
        layers: ['surfaces'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'route.verification',
        kind: 'route',
        title: '/profile/verification',
        subtitle: 'KYC Stripe Identity',
        path: 'frontend/src/app/(country)/[country]/(account)/profile/verification/page.tsx',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_PRO,
    },
    {
        id: 'route.admin',
        kind: 'route',
        title: '/{país}/admin',
        subtitle: 'Panel scoped al país',
        path: 'frontend/src/app/(country)/[country]/(admin)/admin/',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_ADMIN,
    },
    {
        id: 'route.config',
        kind: 'route',
        title: '/config',
        subtitle: 'Admin global SuperAdmin',
        path: 'frontend/src/app/(config)/config/',
        status: 'live',
        layers: ['surfaces'],
        perspectives: P_SA,
        note: 'No son 3 pantallas: replica el catálogo más countries, integrations y app-users.',
    },

    {
        id: 'feature.home',
        kind: 'feature',
        title: 'feature/home',
        subtitle: 'Hero, categorías, destacados',
        path: 'frontend/src/features/home/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_CLIENT,
    },
    {
        id: 'feature.geo',
        kind: 'feature',
        title: 'feature/geo',
        subtitle: 'país, región, localidad',
        path: 'frontend/src/features/geo/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_ALL,
    },
    {
        id: 'feature.auth',
        kind: 'feature',
        title: 'feature/auth',
        subtitle: 'login, OAuth, redirectByRole',
        path: 'frontend/src/features/auth/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_ALL,
    },
    {
        id: 'feature.services',
        kind: 'feature',
        title: 'feature/services',
        subtitle: 'search, ficha, publish, leads',
        path: 'frontend/src/features/services/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'feature.chat',
        kind: 'feature',
        title: 'feature/chat',
        subtitle: 'widget + useChatSocket',
        path: 'frontend/src/features/chat/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'feature.reviews',
        kind: 'feature',
        title: 'feature/reviews',
        subtitle: 'reseña PENDING → ACTIVE',
        path: 'frontend/src/features/reviews/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'feature.favorites',
        kind: 'feature',
        title: 'feature/favorites',
        subtitle: 'guardar anuncio',
        path: 'frontend/src/features/favorites/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_CLIENT,
    },
    {
        id: 'feature.payments',
        kind: 'feature',
        title: 'feature/payments',
        subtitle: 'Brick MP · Stripe Elements',
        path: 'frontend/src/features/payments/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'feature.users',
        kind: 'feature',
        title: 'feature/users',
        subtitle: 'perfil, KYC, addresses',
        path: 'frontend/src/features/users/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'feature.admin',
        kind: 'feature',
        title: 'feature/admin',
        subtitle: 'AdminSidebar, scope país',
        path: 'frontend/src/features/admin/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'feature.integrations',
        kind: 'feature',
        title: 'feature/integrations',
        subtitle: '11 providers en /config',
        path: 'frontend/src/features/integrations/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_SA,
    },
    {
        id: 'feature.configuration',
        kind: 'feature',
        title: 'feature/configuration',
        subtitle: 'países y paymentsEnabled',
        path: 'frontend/src/features/configuration/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_SA,
    },

    {
        id: 'module.geo',
        kind: 'module',
        title: 'modules/geo',
        subtitle: 'países, resolve, Haversine',
        path: 'backend/src/modules/geo/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_ALL,
    },
    {
        id: 'module.auth',
        kind: 'module',
        title: 'modules/auth',
        subtitle: 'login, OAuth, refresh JWT',
        path: 'backend/src/modules/auth/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_ALL,
    },
    {
        id: 'module.services',
        kind: 'module',
        title: 'modules/services',
        subtitle: 'CRUD, search, featured',
        path: 'backend/src/modules/services/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'module.chat',
        kind: 'module',
        title: 'modules/chat',
        subtitle: 'REST + gateway',
        path: 'backend/src/modules/chat/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'module.ratings',
        kind: 'module',
        title: 'modules/ratings',
        subtitle: 'PENDING, promedio',
        path: 'backend/src/modules/ratings/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'module.favorites',
        kind: 'module',
        title: 'modules/favorites',
        subtitle: 'POST/DELETE me/favorites',
        path: 'backend/src/modules/favorites/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_CLIENT,
    },
    {
        id: 'module.interactions',
        kind: 'module',
        title: 'modules/interactions',
        subtitle: 'teléfono, WhatsApp, vistas',
        path: 'backend/src/modules/interactions/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'module.subscriptions',
        kind: 'module',
        title: 'modules/subscriptions',
        subtitle: 'Hireeo Pro + webhooks',
        path: 'backend/src/modules/subscriptions/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'module.payments',
        kind: 'module',
        title: 'modules/payments',
        subtitle: 'gateways MP / Stripe',
        path: 'backend/src/modules/payments/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['profesional', 'tecnica'],
    },
    {
        id: 'module.prices',
        kind: 'module',
        title: 'modules/prices',
        subtitle: 'PremiumPrice por duración',
        path: 'backend/src/modules/prices/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['profesional', 'admin', 'superadmin', 'tecnica'],
    },
    {
        id: 'module.serviceRequests',
        kind: 'module',
        title: 'modules/service-requests',
        subtitle: 'pedidos · alta no está en la web',
        path: 'backend/src/modules/service-requests/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_PRO,
        note: 'La web Next no hace POST de alta. Entra por mobile/API.',
    },
    {
        id: 'module.quotes',
        kind: 'module',
        title: 'modules/quotes',
        subtitle: 'cotizar y aceptar',
        path: 'backend/src/modules/quotes/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'module.escrow',
        kind: 'module',
        title: 'modules/escrow',
        subtitle: '15% / 85% · Connect mock',
        path: 'backend/src/modules/escrow/',
        status: 'mock',
        layers: ['domain'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
        note: 'Split Connect / Marketplace está mockeado en logs.',
    },
    {
        id: 'module.kyc',
        kind: 'module',
        title: 'modules/kyc',
        subtitle: 'Stripe Identity · status en User',
        path: 'backend/src/modules/kyc/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_PRO,
        note: 'No hay tabla Kyc. kycStatus vive en User.',
    },
    {
        id: 'module.users',
        kind: 'module',
        title: 'modules/users',
        subtitle: 'perfil, roles, become-provider',
        path: 'backend/src/modules/users/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_ALL,
    },
    {
        id: 'module.upload',
        kind: 'module',
        title: 'modules/upload',
        subtitle: 'Cloudinary',
        path: 'backend/src/modules/upload/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_PRO,
    },
    {
        id: 'module.chatbot',
        kind: 'module',
        title: 'modules/chatbot',
        subtitle: 'detect-category Gemini',
        path: 'backend/src/modules/chatbot/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_CLIENT,
    },
    {
        id: 'module.integrations',
        kind: 'module',
        title: 'modules/integrations',
        subtitle: 'credenciales cifradas',
        path: 'backend/src/modules/integrations/',
        status: 'live',
        layers: ['domain'],
        perspectives: P_SA,
    },
    {
        id: 'module.categories',
        kind: 'module',
        title: 'modules/categories',
        subtitle: 'árbol de oficios',
        path: 'backend/src/modules/categories/',
        status: 'live',
        layers: ['domain'],
        perspectives: ['cliente', 'admin', 'superadmin', 'tecnica'],
    },

    {
        id: 'ext.mercadopago',
        kind: 'external',
        title: 'MercadoPago',
        subtitle: 'cl · ar · uy',
        path: 'backend/src/modules/payments/gateways/mercadopago.gateway.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: ['profesional', 'cliente', 'tecnica'],
    },
    {
        id: 'ext.stripe',
        kind: 'external',
        title: 'Stripe',
        subtitle: 'es · us',
        path: 'backend/src/modules/payments/gateways/stripe.gateway.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: ['profesional', 'cliente', 'tecnica'],
    },
    {
        id: 'ext.stripeKyc',
        kind: 'external',
        title: 'Stripe Identity',
        subtitle: 'KYC hosted',
        path: 'backend/src/modules/kyc/stripe-identity.gateway.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: P_PRO,
    },
    {
        id: 'ext.cloudinary',
        kind: 'external',
        title: 'Cloudinary',
        subtitle: 'fotos del anuncio',
        path: 'backend/src/modules/upload/',
        status: 'live',
        layers: ['externals'],
        perspectives: P_PRO,
    },
    {
        id: 'ext.gemini',
        kind: 'external',
        title: 'Gemini',
        subtitle: 'categoría y copy IA',
        path: 'backend/src/modules/chatbot/',
        status: 'live',
        layers: ['externals'],
        perspectives: ['cliente', 'profesional', 'tecnica'],
    },
    {
        id: 'ext.firebase',
        kind: 'external',
        title: 'Firebase FCM',
        subtitle: 'push',
        path: 'backend/src/modules/notifications/',
        status: 'live',
        layers: ['externals'],
        perspectives: ['tecnica'],
    },
    {
        id: 'ext.brevo',
        kind: 'external',
        title: 'Brevo',
        subtitle: 'email transaccional',
        path: 'backend/src/modules/email/',
        status: 'live',
        layers: ['externals'],
        perspectives: ['tecnica', 'superadmin'],
    },
    {
        id: 'ext.google',
        kind: 'external',
        title: 'Google OAuth',
        subtitle: 'si hay Integration',
        path: 'frontend/src/features/auth/lib/oauth-providers.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: P_ALL,
    },
    {
        id: 'ext.apple',
        kind: 'external',
        title: 'Apple OAuth',
        subtitle: 'si hay Integration',
        path: 'frontend/src/features/auth/lib/oauth-providers.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: P_ALL,
    },
    {
        id: 'ext.azure',
        kind: 'external',
        title: 'Azure AD',
        subtitle: 'Microsoft login',
        path: 'frontend/src/features/auth/lib/oauth-providers.ts',
        status: 'live',
        layers: ['externals'],
        perspectives: P_ALL,
    },
];
