export const CL_SEED = {
    country: {
        code: 'cl',
        name: 'Chile',
        currency: 'CLP',
        locale: 'es-CL',
        timezone: 'America/Santiago',
        gateway: 'MERCADOPAGO' as const,
        regionLabel: 'Región',
        localityLabel: 'Comuna',
    },
    regions: [
        {
            name: 'Arica y Parinacota',
            code: 'AP',
            localities: [
                { name: 'Arica', slug: 'arica' },
                { name: 'Putre', slug: 'putre' },
                { name: 'General Lagos', slug: 'general-lagos' },
            ],
        },
        {
            name: 'Tarapacá',
            code: 'TA',
            localities: [
                { name: 'Iquique', slug: 'iquique' },
                { name: 'Alto Hospicio', slug: 'alto-hospicio' },
                { name: 'Pozo Almonte', slug: 'pozo-almonte' },
                { name: 'Pica', slug: 'pica' },
            ],
        },
        {
            name: 'Antofagasta',
            code: 'AN',
            localities: [
                { name: 'Antofagasta', slug: 'antofagasta' },
                { name: 'Calama', slug: 'calama' },
                { name: 'Tocopilla', slug: 'tocopilla' },
                { name: 'San Pedro de Atacama', slug: 'san-pedro-de-atacama' },
            ],
        },
        {
            name: 'Atacama',
            code: 'AT',
            localities: [
                { name: 'Copiapó', slug: 'copiapo' },
                { name: 'Vallenar', slug: 'vallenar' },
                { name: 'Caldera', slug: 'caldera' },
                { name: 'Chañaral', slug: 'chanaral' },
            ],
        },
        {
            name: 'Coquimbo',
            code: 'CO',
            localities: [
                { name: 'La Serena', slug: 'la-serena' },
                { name: 'Coquimbo', slug: 'coquimbo' },
                { name: 'Ovalle', slug: 'ovalle' },
                { name: 'Illapel', slug: 'illapel' },
                { name: 'Vicuña', slug: 'vicuna' },
                { name: 'Andacollo', slug: 'andacollo' },
            ],
        },
        {
            name: 'Valparaíso',
            code: 'VA',
            localities: [
                { name: 'Valparaíso', slug: 'valparaiso' },
                { name: 'Viña del Mar', slug: 'vina-del-mar' },
                { name: 'Quilpué', slug: 'quilpue' },
                { name: 'San Antonio', slug: 'san-antonio-va' },
                { name: 'Quillota', slug: 'quillota' },
                { name: 'Los Andes', slug: 'los-andes-va' },
                { name: 'La Calera', slug: 'la-calera' },
            ],
        },
        {
            name: 'Metropolitana de Santiago',
            code: 'RM',
            localities: [
                { name: 'Santiago', slug: 'santiago' },
                { name: 'Maipú', slug: 'maipu' },
                { name: 'Puente Alto', slug: 'puente-alto' },
                { name: 'La Florida', slug: 'la-florida' },
                { name: 'Las Condes', slug: 'las-condes' },
                { name: 'Ñuñoa', slug: 'nunoa' },
                { name: 'San Bernardo', slug: 'san-bernardo' },
                { name: 'Peñalolén', slug: 'penalolen' },
                { name: 'Providencia', slug: 'providencia' },
                { name: 'La Pintana', slug: 'la-pintana' },
                { name: 'El Bosque', slug: 'el-bosque' },
                { name: 'Pudahuel', slug: 'pudahuel' },
            ],
        },
        {
            name: "O'Higgins",
            code: 'LI',
            localities: [
                { name: 'Rancagua', slug: 'rancagua' },
                { name: 'San Fernando', slug: 'san-fernando' },
                { name: 'Pichilemu', slug: 'pichilemu' },
                { name: 'Rengo', slug: 'rengo' },
            ],
        },
        {
            name: 'Maule',
            code: 'ML',
            localities: [
                { name: 'Talca', slug: 'talca' },
                { name: 'Curicó', slug: 'curico' },
                { name: 'Linares', slug: 'linares' },
                { name: 'Cauquenes', slug: 'cauquenes' },
                { name: 'Constitución', slug: 'constitucion-ml' },
            ],
        },
        {
            name: 'Ñuble',
            code: 'NB',
            localities: [
                { name: 'Chillán', slug: 'chillan' },
                { name: 'Chillán Viejo', slug: 'chillan-viejo' },
                { name: 'San Carlos', slug: 'san-carlos-nb' },
                { name: 'Bulnes', slug: 'bulnes' },
            ],
        },
        {
            name: 'Biobío',
            code: 'BI',
            localities: [
                { name: 'Concepción', slug: 'concepcion-bi' },
                { name: 'Talcahuano', slug: 'talcahuano' },
                { name: 'Los Ángeles', slug: 'los-angeles-bi' },
                { name: 'Hualpén', slug: 'hualpen' },
                { name: 'Coronel', slug: 'coronel' },
                { name: 'San Pedro de la Paz', slug: 'san-pedro-de-la-paz' },
            ],
        },
        {
            name: 'La Araucanía',
            code: 'AR',
            localities: [
                { name: 'Temuco', slug: 'temuco' },
                { name: 'Villarrica', slug: 'villarrica' },
                { name: 'Pucón', slug: 'pucon' },
                { name: 'Angol', slug: 'angol' },
                { name: 'Padre Las Casas', slug: 'padre-las-casas' },
            ],
        },
        {
            name: 'Los Ríos',
            code: 'LR',
            localities: [
                { name: 'Valdivia', slug: 'valdivia' },
                { name: 'La Unión', slug: 'la-union' },
                { name: 'Panguipulli', slug: 'panguipulli' },
                { name: 'Río Bueno', slug: 'rio-bueno' },
            ],
        },
        {
            name: 'Los Lagos',
            code: 'LL',
            localities: [
                { name: 'Puerto Montt', slug: 'puerto-montt' },
                { name: 'Osorno', slug: 'osorno' },
                { name: 'Castro', slug: 'castro' },
                { name: 'Ancud', slug: 'ancud' },
                { name: 'Puerto Varas', slug: 'puerto-varas' },
                { name: 'Quellón', slug: 'quellon' },
                { name: 'Dalcahue', slug: 'dalcahue' },
                { name: 'Chonchi', slug: 'chonchi' },
                { name: 'Curaco de Vélez', slug: 'curaco-de-velez' },
                { name: 'Puqueldón', slug: 'puqueldon' },
                { name: 'Queilén', slug: 'queilen' },
                { name: 'Quemchi', slug: 'quemchi' },
                { name: 'Quinchao', slug: 'quinchao' },
                { name: 'Fresia', slug: 'fresia' },
            ],
        },
        {
            name: 'Aysén',
            code: 'AI',
            localities: [
                { name: 'Coyhaique', slug: 'coyhaique' },
                { name: 'Puerto Aysén', slug: 'puerto-aysen' },
                { name: 'Chile Chico', slug: 'chile-chico' },
            ],
        },
        {
            name: 'Magallanes',
            code: 'MA',
            localities: [
                { name: 'Punta Arenas', slug: 'punta-arenas' },
                { name: 'Puerto Natales', slug: 'puerto-natales' },
                { name: 'Porvenir', slug: 'porvenir' },
            ],
        },
    ],
};
