'use client';

import {
    Award,
    Battery,
    Bug,
    Cake,
    Camera,
    Car,
    ChefHat,
    Clipboard,
    Database,
    Disc,
    Dog,
    Droplets,
    Dumbbell,
    FileText,
    Footprints,
    GraduationCap,
    Hammer,
    Hand,
    HardHat,
    Heart,
    Home,
    Key,
    Languages,
    Laptop,
    Leaf,
    Mail,
    Monitor,
    MoreHorizontal,
    Music,
    Paintbrush,
    Palette,
    Phone,
    Salad,
    Scale,
    Scissors,
    Smartphone,
    Sparkles,
    Square,
    Stethoscope,
    Syringe,
    Thermometer,
    Trash,
    Truck,
    User,
    Utensils,
    Waves,
    Wifi,
    Zap,
} from '@/shared/components/icons';
import type { IconProps, SvgIconComponent } from '@/shared/components/icons';

const CATEGORY_ICON_MAP: Record<string, SvgIconComponent> = {
    Award,
    Battery,
    Bug,
    Cake,
    Camera,
    Car,
    ChefHat,
    Clipboard,
    Database,
    Disc,
    Dog,
    Droplets,
    Dumbbell,
    FileText,
    Footprints,
    GraduationCap,
    Hammer,
    Hand,
    HardHat,
    Heart,
    Home,
    Key,
    Languages,
    Laptop,
    Leaf,
    Mail,
    Monitor,
    MoreHorizontal,
    Music,
    Paintbrush,
    Palette,
    Phone,
    Salad,
    Scale,
    Scissors,
    Smartphone,
    Sparkles,
    Square,
    Stethoscope,
    Syringe,
    Thermometer,
    Trash,
    Truck,
    User,
    Utensils,
    Waves,
    Wifi,
    Zap,
};

export type CategoryIconName = keyof typeof CATEGORY_ICON_MAP;

export const ICON_NAMES = Object.keys(CATEGORY_ICON_MAP) as CategoryIconName[];

interface CategoryIconComponentProps extends Omit<IconProps, 'name'> {
    name: string | null | undefined;
}

export const CategoryIcon = ({ name, ...props }: CategoryIconComponentProps) => {
    const Icon = CATEGORY_ICON_MAP[name ?? ''] ?? MoreHorizontal;
    return <Icon {...props} />;
};

export const ALL_CATEGORIES_DATA = [
    { nombre: 'Gasfitería / Fontanería', slug: 'gasfiteria', icono: 'Droplets' },
    { nombre: 'Electricidad e Iluminación', slug: 'electricidad', icono: 'Zap' },
    { nombre: 'Cerrajería', slug: 'cerrajeria', icono: 'Key' },
    { nombre: 'Carpintería y Mueblista', slug: 'carpinteria', icono: 'Hammer' },
    { nombre: 'Pintura y Papel Mural', slug: 'pintura', icono: 'Paintbrush' },
    { nombre: 'Albañilería y Pisos', slug: 'albanileria', icono: 'HardHat' },
    { nombre: 'Vidriería y Aluminio', slug: 'vidrieria', icono: 'Square' },
    { nombre: 'Reparación de Techos y Goteras', slug: 'techos', icono: 'Home' },
    { nombre: 'Limpieza de Fachadas y Canaletas', slug: 'limpieza-fachadas', icono: 'Home' },
    { nombre: 'Destape de Desagües', slug: 'destapes', icono: 'Droplets' },
    { nombre: 'Climatización', slug: 'climatizacion', icono: 'Thermometer' },
    { nombre: 'Reparación de Electrodomésticos', slug: 'linea-blanca', icono: 'Smartphone' },
    { nombre: 'Limpieza de Hogar', slug: 'limpieza-hogar', icono: 'Sparkles' },
    { nombre: 'Limpieza de Tapices y Alfombras', slug: 'limpieza-tapices', icono: 'Waves' },
    { nombre: 'Fumigación y Control de Plagas', slug: 'fumigacion', icono: 'Bug' },
    { nombre: 'Jardinería y Paisajismo', slug: 'jardineria', icono: 'Leaf' },
    { nombre: 'Poda y Corte de Árboles', slug: 'poda', icono: 'Scissors' },
    { nombre: 'Mantención de Piscinas', slug: 'piscinas', icono: 'Waves' },
    { nombre: 'Riego Automático', slug: 'riego', icono: 'Droplets' },
    { nombre: 'Peluquería y Barbería', slug: 'peluqueria', icono: 'Scissors' },
    { nombre: 'Manicure y Pedicure', slug: 'manicure', icono: 'Sparkles' },
    { nombre: 'Maquillaje y Peinado', slug: 'maquillaje', icono: 'User' },
    { nombre: 'Depilación', slug: 'depilacion', icono: 'User' },
    { nombre: 'Tratamientos Faciales y Corporales', slug: 'estetica', icono: 'Heart' },
    { nombre: 'Masajes', slug: 'masajes', icono: 'Hand' },
    { nombre: 'Enfermería a Domicilio', slug: 'enfermeria', icono: 'Syringe' },
    { nombre: 'Cuidado de Adultos Mayores', slug: 'cuidado-adultos', icono: 'Heart' },
    { nombre: 'Podología', slug: 'podologia', icono: 'Footprints' },
    { nombre: 'Entrenador Personal / Yoga / Pilates', slug: 'entrenamiento', icono: 'Dumbbell' },
    { nombre: 'Nutrición y Dietética', slug: 'nutricion', icono: 'Salad' },
    { nombre: 'Peluquería y Baño de Mascotas', slug: 'peluqueria-mascotas', icono: 'Dog' },
    { nombre: 'Veterinaria a Domicilio', slug: 'veterinaria', icono: 'Stethoscope' },
    { nombre: 'Paseadores de Perros', slug: 'paseadores', icono: 'Dog' },
    { nombre: 'Cuidadores y Hotelería (Pet Sitting)', slug: 'pet-sitting', icono: 'Home' },
    { nombre: 'Adiestramiento Canino', slug: 'adiestramiento', icono: 'Award' },
    { nombre: 'Lavado de Autos (Car Wash)', slug: 'car-wash', icono: 'Car' },
    { nombre: 'Mecánica Ligera y Mantención', slug: 'mecanica', icono: 'Hammer' },
    { nombre: 'Baterías y Carga', slug: 'baterias', icono: 'Battery' },
    { nombre: 'Vulcanización y Neumáticos', slug: 'vulcanizacion', icono: 'Disc' },
    { nombre: 'Grúas y Remolque', slug: 'gruas', icono: 'Truck' },
    { nombre: 'Soporte Técnico Computacional', slug: 'soporte-tecnico', icono: 'Laptop' },
    { nombre: 'Instalación de Cámaras y Alarmas', slug: 'seguridad', icono: 'Camera' },
    { nombre: 'Redes, WiFi y Domótica', slug: 'redes', icono: 'Wifi' },
    { nombre: 'Recuperación de Datos', slug: 'recuperacion-datos', icono: 'Database' },
    { nombre: 'Banquetería y Catering', slug: 'banqueteria', icono: 'Utensils' },
    { nombre: 'Tortas, Pastelería y Repostería', slug: 'pasteleria', icono: 'Cake' },
    { nombre: 'Chef a Domicilio', slug: 'chef', icono: 'ChefHat' },
    { nombre: 'Decoración y Ambientación', slug: 'decoracion', icono: 'Palette' },
    { nombre: 'Animación y DJs', slug: 'animacion', icono: 'Music' },
    { nombre: 'Fotografía y Video de Eventos', slug: 'fotografia', icono: 'Camera' },
    { nombre: 'Reforzamiento Escolar', slug: 'reforzamiento', icono: 'GraduationCap' },
    { nombre: 'Idiomas', slug: 'idiomas', icono: 'Languages' },
    { nombre: 'Clases de Música e Instrumentos', slug: 'clases-musica', icono: 'Music' },
    { nombre: 'Clases de Arte y Manualidades', slug: 'clases-arte', icono: 'Palette' },
    { nombre: 'Fletes y Mudanzas', slug: 'fletes', icono: 'Truck' },
    { nombre: 'Retiro de Escombros y Cachureos', slug: 'escombros', icono: 'Trash' },
    { nombre: 'Mensajería y Encomiendas', slug: 'mensajeria', icono: 'Mail' },
    { nombre: 'Trámites y Gestoría', slug: 'tramites', icono: 'Clipboard' },
    { nombre: 'Contabilidad y Finanzas', slug: 'contabilidad', icono: 'FileText' },
    { nombre: 'Asesoría Legal / Abogados', slug: 'legal', icono: 'Scale' },
    { nombre: 'Diseño Gráfico y Web', slug: 'diseno', icono: 'Monitor' },
    { nombre: 'Otros', slug: 'otros', icono: 'MoreHorizontal' },
];
